export const LISTING_CATEGORIES = {
  'Education': [
    'Support',
    'Access',
    'Alternative Education',
    'Specialized Education',
  ],
  'Care & Safety': [
    'Domestic Violence & Sexual Assault',
    'Pet Care',
    'Mobile Crisis Services',
    'Child Care',
  ],
  'Day Services & Drop-in': [
    'Restrooms',
    'Mail',
    'Drop-in Spaces',
  ],
  'Financial': [
    'Financial Assistance',
    'Utility Assistance',
    'Other',
  ],
  'Housing & Shelter': [
    'Housing Services',
    'Renters Services',
    'Shelters',
    'Severe Emergency Weather Shelter',
    'Camps & Villages',
    'Transitional Housing',
  ],
  'Health & Wellness': [
    'Dental',
    'HIV / AIDS',
    'Recovery Services',
    'Student Health Centers',
    'Syringe Exchange',
    'Reproductive Health',
  ],
  'Mental Health': [
    'Counseling & Mediation',
    'Support Groups',
    'Family Services',
    'Residential Programs',
    'Comprehensive Services',
  ],
  'Leadership Opportunities': [
    'Committees, Councils, & Boards',
    'Leadership Development Training',
    'Political Action & Social Justice',
    'Community Development & Improvement',
    'Education & Academic',
    'Culturally Specific',
    'Rural Community',
    'Paid Opportunity',
    'Internship',
    'Summer-based Opportunity',
  ],
  'Legal': [
    'Legal Services',
    'Know Your Rights',
    'Property Recovery',
    'Juvenile Justice & Rehabilitation',
  ],
  'Necessities': [
    'Clothing',
    'Hygiene Products',
    'Other Goods and Services',
  ],
  'Specialized Assistance': [
    'LGBTQIA2+',
    'Veteran Services',
    'Family Services',
    'Disability Resource Centers',
    'Cultural Centers',
    'Faith Based',
    'Foster Care',
    'Pregnancy & Parenting Services',
    'Disability & Chronic Illness',
  ],
  'Transportation': [
    'Ride Connection',
    'Medical Transport',
    'Public Transportation Assistance',
  ],
  'Work & Employment': [
    'Job Seekers',
    'Employment Training',
    'Social Security & Disability',
    'Work Experience',
  ],
}