export const CATEGORY_ICONS = {
  "Care & Safety": "hand holding heart",
  "Day Services & Drop-in": "sun", 
  "Education": "graduation cap", 
  "Financial": "money bill alternate outline", 
  "Food": "utensils",
  "Health & Wellness": "plus", 
  "Housing & Shelter": "home", 
  "Leadership Opportunities": "flag", 
  "Legal": "balance scale", 
  "Mental Health": "heartbeat", 
  "More": "info circle",
  "Other": "info circle",
  "Population Specific": "handshake", 
  "Specialized Assistance": "handshake", 
  "Social Services": "users", 
  "Work & Employment": "briefcase", 
}
